# This file contains port mapping to host.
# It is excluded into dedicated file so it can be omitted, allowing
# developer to run multiple instances of runtime environment
# (eg when using git worktree)
---
service:
  app:
    command: /docker-entrypoint.sh
    ports:
      - 3000:3000

